### PR TITLE
[PLAT-476] Fix/sliders

### LINKED ISSUE #162: Optimize row distance filter
the distance filter needs some updating:
- use new drawing
- fewer calculations?
- investigate clashes with `delete_polygon` mode
  - drawing polygon is very laggy, and each new delete polygon un-deprecates previously deleted items

### PR DESCRIPTION
**Pull request by TrevorBurgoyne**
# Slider Performance Improvements and Bug Fixes
[PLAT-476](https://sentera.atlassian.net/browse/PLAT-476)

## Description
- Closes #162 
- Improvements to performance of the `FilterDistance` Toolbox item:
  - Switch to new redrawing util functions and only redraw annotations when necessary
  - Greatly reduce the number of distance calculations by only calculating distances for the newly modified annotation (polyline or point), 
    rather than recalculating all distances for all annotations everytime.
  - Each point now tracks the `id` of the closest line in each class to further reduce the number of redundant calculations.
- Improvements to performance of the `KeypointSlider` Toolbox item:
  - Switch to new redrawing util functions and only redraw annotations when necessary
- Fix bug where `delete` modes and the `FilterDistance` toolbox item would clash.
- Expose `n_annos_per_canvas` arg to `config_data` as an advanced feature for performance tuning.
  - Also added some dynamic scaling of this value based on the max number of annotations in a single subtask if no value is provided by the user.
- Added `disable_multi_class_mode` flag to `FilterDistanceConfig`, which defaults to `false`. When `true`, the multi-class mode will be disabled and the checkbox will not be shown.
- Added `filter_during_polyline_move` flag to `FilterDistanceConfig`, which defaults to `true`. When `false`, the filter/overlay will not be updated until polyline moves/edits are completed. This can be useful for boosting performance when working with many annotations.
  - This option is also present as a checkbox option in the `FilterDistance` toolbox item.

## Breaking Changes
- Renamed `FilterDistanceConfig` arg `show_overlay_on_load` -> `show_overlay` for internal consistency.
- Changed format of `default_values` arg in `FilterDistanceConfig`. The name for the single class mode default has changed from `"single"` -> `"closest_row"`, and each entry in the object should be a `DistanceFromPolyline` object (`{distance: <number>}`), rather than a single number. See the updated `api_spec.md` for more details.
- `KeypointSlider` now works on all points in every subtask, even when the subtask is not active.
- Deprecated the `new` and `is_new` fields in `ULabelAnnotation`. There was internal inconsistency in their use, and some internal logic that depended on them was buggy and was sometimes preventing the `FilterDistance` slider from working as expected.

## PR Checklist

- [x] Merged latest main
- [x] Version number in `package.json` has been bumped since last release
- [x] Version numbers match between package `package.json` and `src/version.js`
- [x] Ran `npm install` and `npm run build` AFTER bumping the version number
- [x] Updated documentation if necessary (currently just in `api_spec.md`)
- [x] Added changes to `changelog.md`

[PLAT-476]: https://sentera.atlassian.net/browse/PLAT-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: src/annotation_operators.ts [hunk 1]
```diff
@@ -238,56 +237,144 @@ function get_distance_from_point_to_line(point_annotation: ULabelAnnotation, lin
...
+ * Update the distance from a single line to each point annotation.
+ * If a line was previously the closest line to a point, then the distance from that point to ALL lines will be recalculated.
+ * Used when a single polyline is modified.
+ * 
+ * @param line_annotation line annotation
+ * @param point_annotations all point annotations
+ * @param all_line_annotations all line annotations
+ * @param offset offset of the line annotation
+ */
+export function update_distance_from_line_to_each_point(
```
Comment (TrevorBurgoyne) [inline src/annotation_operators.ts:313]: When a line is updated, we don't have to update *all* the distances from every point to every line. Instead:
- For points that had the line as one of its saved ids in its `distance_from`, we recalculate that point's distance to EVERY line, since the current line may have moved farther away.
- For points that do NOT have the line as one of its saved ids, we can simply check if the current line's distance to the point is smaller than that of any of the point's saved distances.

File: src/annotation_operators.ts [hunk 2]
```diff
@@ -238,56 +237,144 @@ function get_distance_from_point_to_line(point_annotation: ULabelAnnotation, lin
...
+/**
+ * Assigns a single point annotation a distance to the closest polyline
+ * from each diffrent class of polyline, as well as the distance from
+ * the closest line, regardless of class.
+ * 
+ * @param point_annotation single point annotation
+ * @param line_annotations set of line annotations
+ * @param offset Offset of a particular annotation in the set. Used when an annotation is being moved by the user
+ */
+export function assign_closest_line_to_single_point(
```
Comment (TrevorBurgoyne) [inline src/annotation_operators.ts:267]: When a point is updated, we need to recalculate its distance to every line

File: src/index.js [hunk 3]
```diff
@@ -1505,6 +1513,75 @@ export class ULabel {
...
+        if (this.toolbox_order.includes(AllowedToolboxItem.FilterDistance)) {
+            // Add id to the offset
+            if (offset !== null) {
+                offset["id"] = annotation_id;
+            }
+
+            if (force_filter_all) {
+                // Filter all points from all lines
+                // Used when a line is deleted
+                filter_points_distance_from_line(this, true, offset);
```
Comment (TrevorBurgoyne) [inline src/index.js:1536]: When a line is deleted, we recalculate the distances of all points to all lines

File: src/toolbox.ts [hunk 4]
```diff
@@ -1999,56 +2017,36 @@ export class FilterPointDistanceFromRow extends ToolboxItem {
...
-
-        // Loop through every key value pair in the config
-        for (const [key, value] of Object.entries(this.config)) {
-            // If the passed in value's type !== the default value's type then use the default value
-            if (typeof value !== typeof default_values[key]) {
-                this.config[key] = default_values[key]
+        // For each key missing from the config, set the default value
+        for (const key in DEFAULT_FILTER_DISTANCE_CONFIG) {
+            if (!this.config.hasOwnProperty(key)) {
+                this.config[key] = DEFAULT_FILTER_DISTANCE_CONFIG[key]
```
Comment (joshua-dean) [inline src/toolbox.ts:2023]: Is it a big lift to just make this a class with defaults? Or do we foresee multiple sets of defaults for this?

File: src/toolbox.ts [hunk 5]
```diff
@@ -1999,56 +2017,36 @@ export class FilterPointDistanceFromRow extends ToolboxItem {
...
-        }
-        else if (window.localStorage.getItem("filterDistanceShowOverlay") === "false") {
-            this.show_overlay = false
-            this.overlay.update_display_overlay(false)
-        }
-        else if (this.config.show_overlay_on_load !== undefined || this.config.show_overlay_on_load !== null) {
-            this.show_overlay = this.config.show_overlay_on_load
+
+        // Check if localStorage has a value for showing the overlay
+        if (window.localStorage.getItem("filterDistanceShowOverlay") !== null) {
```
Comment (joshua-dean) [inline src/toolbox.ts:2042]: Would it be worth pulling these into a separate interface with types so we don't need to access it with strings?
We only use it here in `toolbox.ts`, but it does have a fair amount of calls. 
Also should probably standardize on `window.localStorage` vs `localStorage`.

File: src/index.js [hunk 6]
```diff
@@ -1290,7 +1298,7 @@ export class ULabel {
                     $("#" + this.config["imwrap_id"]).prepend(this.filter_distance_overlay.get_canvas())
                     
                     // Filter the points with an override
-                    filter_points_distance_from_line(this, null, {
+                    filter_points_distance_from_line(this, true, null, {
```
Comment (joshua-dean) [inline src/index.js:1301]: So this is `create_overlays`, which is called by `init`. It looks like `set_annotations` does call `update_filter_distance`, and should be calling this similarly, as long as the toolbox properly includes the `FilterDistanceItem` (is the toolbox loaded at that point?).

Are there any ways to perform an "in-place" reload that could end up not properly calling this?

Might be related to the QASM reloading issue (that doesn't appear to be present in `v0.11.0`).

**Review by joshua-dean — COMMENTED** [review]
So with `n` polylines and `m` points, loading is still `O(n*m)`, and edits are `O(m)` and `O(n)` respectively.

Definitely a solid improvement.

File: src/index.js (hunk 6 above)
Comment (TrevorBurgoyne) [reply src/index.js:1301]: I haven't pushed the `set_annotations` fix to the qasm site yet, i suspect that was the issue.

I am tracking down a bug right now that I think has to do with this `create_overlays` call. To reproduce:

1) Open a fresh instance of the `0.12.0` site
2) Enable both `Show Filter Range` and `Filter During Move` (to make the bug easier to detect)
3) Move a row. Some points will stay visible when they should be deprecated.

But if you follow the same steps and instead first delete/create a row (operations that force a recalc of all distances) before moving a row, the bug disappears

File: src/annotation_operators.ts [hunk 7]
```diff
@@ -238,56 +237,161 @@ function get_distance_from_point_to_line(point_annotation: ULabelAnnotation, lin
...
+    point_annotation: ULabelAnnotation,
+    line_annotations: ULabelAnnotation[],
+    offset: Offset = null
+) {
+    // Create a new distance_from object for the point annotation
+    let distance_from: DistanceFromPolylineClasses = {closest_row: {distance: Infinity}}
```
[the remark this answers is not in the document]
Comment (TrevorBurgoyne) [reply src/annotation_operators.ts:273]: yeah this was a fix to prevent errors when there are no lines. as far as i can tell there should be no issues, bc the distance is always just used for comparisons

File: src/index.js (hunk 6 above)
Comment (TrevorBurgoyne) [reply src/index.js:1298]: in local testing i thought this might be due to `move/edit/delete` logic sometime creating a new `annotation_id`, which was preventing the `polyline_id` from matching correctly as so points weren't updating their distances. But the bug still seems to be present on the site so 🤷

Comment (joshua-dean) [reply src/index.js:1298]: I see this on the demo site, but not when running `row-filtering-example` on the local demo.

Comment (TrevorBurgoyne) [reply src/index.js:1298]: jk looks like its fixed now. site just hadnt updated with my changes

Comment (joshua-dean) [reply src/index.js:1298]: Yup, I agree. Prior to 1046840 I could reproduce, and now it appears to be gone.

Comment (joshua-dean) [reply src/index.js:1298]: In-place reloading on QASM also appears fixed

File: src/toolbox.ts (hunk 5 above)
Comment (TrevorBurgoyne) [reply src/toolbox.ts]: [fd70506](https://github.com/SenteraLLC/ulabel/pull/167/commits/fd70506e3335b0d5cf55d65e85ac0818041402a8)

File: src/toolbox.ts (hunk 4 above)
Comment (TrevorBurgoyne) [reply src/toolbox.ts:2027]: I reworked this because before there were defaults in two places: `configuration.ts` and `toolbox.ts`. Is your suggestion that the defaults should just be in `toolbox.ts`? I don't feel strongly either way. I went with `configuration.ts` since that's where all the other constructor arg defaults are gathered, but could be convinced that we should move it here.

Comment (joshua-dean) [reply src/toolbox.ts:2027]: Well, on account of `toolbox.ts` being very big, and it being logical to keep all configurable settings in one place, this is fine.

Copying from a default like this is the part that feels weird - if there was a generic function for applying anything that matched the config type, that then got passed `DEFAULT_FILTER_DISTANCE_CONFIG`, I'd feel a little better about it. Getting a little bit nit-picky though, so we can also punt on this if you're not concerned.

Comment (joshua-dean) [reply src/toolbox.ts:2027]: Yeah thinking about it further, punt for now. It will come up if the `ToolboxItem` hierarchy ever gets reworked/separated into their own files.
