### PR TITLE
fix/submit-button-special-chars

### LINKED ISSUE #226: Special Characters in Submit Button Names
Steps to reproduce:
1. Add a special character to the submit button name (e.g. parentheses), like `"name": "Submit (Potatoe)"`

Image

It appears that the name is being directly mapped to an ID, as seen [here](https://github.com/SenteraLLC/ulabel/blob/3c9660272808c11bf4e9fb6f910195b29bd013da/src/toolbox.ts#L2614).

Possible fixes (and drawbacks):
1. Remove special characters when using as the ID
    - Could create collisions, although unlikely
2. Use a different ID entirely (e.g. submit button index)
    - Maybe slightly harder to debug and/or write external code that uses the submit buttons
3. Create a separate "display name" attribute
    - More effort for the user 
5. Remove special characters for both display and ID
    - Feels wrong

  @TrevorBurgoyne I'm going to cook up solution (1.) unless you have objections

### PR DESCRIPTION
**Pull request by joshua-dean**
# Allow special characters in submit buttons

## Description

Closes #226

Also moved submit buttons toolbox item to own file, `toolbox.ts` is getting long and there's not much benefit in having them all in one file vs one directory.

As I moved the file, the relevant diff is in commit 9c1552b

## PR Checklist

- [X] Merged latest main
- [X] Version number in `package.json` has been bumped since last release
- [X] Version numbers match between package `package.json` and `src/version.js`
- [X] Ran `npm install` and `npm run build` AFTER bumping the version number
- [X] Updated documentation if necessary (currently just in `api_spec.md`)
- [X] Added changes to `changelog.md`

## Breaking API Changes

negative

### CODE REVIEW

File: src/toolbox_items/submit_buttons.ts [hunk 1]
```diff
@@ -0,0 +1,239 @@
...
+     */
+    public static submit_button_id(submit_button: ULabelSubmitButton) {
+        // Remove everything except alphanumeric, dash, underscore, space
+        let submit_button_id = submit_button.name.replace(/[^a-zA-Z0-9-_ ]/g, "");
+
+        // Spaces to dashes
+        submit_button_id = submit_button_id.replace(" ", "-");
+
+        return submit_button_id;
+    }
```
Comment (TrevorBurgoyne) [inline src/toolbox_items/submit_buttons.ts:167]: Two thoughts here:

1) previously, we used `replaceLowerConcat` to make the ID all lowercase. I prefer no caps in IDs in general, and in this case it would be nice to keep that in case there are those accessing the button ID directly.

2) When the button name ends with special characters, the ID ends up with a trailing `-` 
`Approve (✔️)` -> `Approve-`
Preferred would be stripping the string of trailing whitespace before replacing spaces with "-"

**Review by TrevorBurgoyne — COMMENTED** [review]
I like the move towards splitting up `toolbox.ts`. Fix works in my testing, just some small nitpick comments

File: src/toolbox_items/submit_buttons.ts (hunk 1 above)
Comment (joshua-dean) [reply src/toolbox_items/submit_buttons.ts]: 545bfeb fixes both of those up
